inits:
  grid:
    head|init|type: ["proper", "xavier", "kaiming"]
    head|init|mode: ["fan_in", "fan_out"]
    head|init|dist_type: ["uniform", "normal"]

baseline_new:
  grid:
    batch_size: [10]

zsl:
  # search_type: "random"
  # num_experiments: 200
  grid:
    # val_ratio: [0.1, 0.15, 0.2]
    max_num_epochs: [25]
    optim|kwargs|lr: [0.005, 0.004, 0.003, 0.002, 0.001]
    bn_affine: [false]
    # optim|scheduler|step_size: [50, 100, 250]
    # optim|scheduler|gamma: [0.1, 0.2, 0.5, 0.9]
    label_smoothing: [0.9, 1.0]
    batch_size: [128, 512]
    hid_dim: [256, 512]
    scale: [5]
