inits:
  grid:
    head|init|type: ["proper", "xavier", "kaiming"]
    head|init|mode: ["fan_in", "fan_out"]

xavier:
  grid:
    head|init|type: ["xavier"]

several_runs:
  grid: {dummy_property: [0]}

other_inits:
  grid:
    init|type: ["kaiming", "xavier"]
    init|mode: ["fan_in", "fan_out"]
    has_bn: [false]

other_inits_bn:
  grid:
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    init|type: ["kaiming", "xavier"]
    init|mode: ["fan_in", "fan_out"]
    has_bn: [true]
    bn_affine: [true]

no_bn_ablation:
  grid:
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    has_bn: [false]

other_inits_sn:
  grid:
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    init|type: ["kaiming", "xavier"]
    init|mode: ["fan_in", "fan_out"]
    has_bn: [true]
    bn_affine: [false]

dn:
  search_type: "random"
  num_experiments: 300
  grid:
    has_bn: [false]
    has_dn: [true]
    init|type: ["kaiming"]
    init|mode: ["fan_out"]

    grad_clip_val: [1, 5, 10, 25, 50, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    optim|scheduler|step_size: [10, 25, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    cross_entropy_reg_coef: [0., 0.01, 0.001]
    entropy_reg_coef: [0., 0.01, 0.001]
    label_smoothing: [0.5, 0.9, 0.95, 0.99, 1.0]
    batch_size: [64, 128, 256, 512]
    hid_dim: [128, 256, 512, 1024]


zsl:
  search_type: "random"
  num_experiments: 100
  grid:
    grad_clip_val: [1, 5, 10, 25, 50, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    optim|scheduler|step_size: [10, 25, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    cross_entropy_reg_coef: [0., 0.01, 0.001]
    entropy_reg_coef: [0., 0.01, 0.001]
    label_smoothing: [0.5, 0.9, 0.95, 0.99, 1.0]
    batch_size: [64, 128, 256, 512]
    hid_dim: [128, 256, 512, 1024]


zsl_linear_ns_no_std:
  search_type: "random"
  num_experiments: 100

  grid:
    model_type: "linear"
    init|type: ["xavier"]
    normalize_and_scale: [true]
    standardize_attrs: [false]

    grad_clip_val: [10, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.001, 0.0005]
    optim|scheduler|step_size: [10, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    batch_size: [128, 256, 512]

zsl_linear_ns_std:
  search_type: "random"
  num_experiments: 100

  grid:
    model_type: "linear"
    init|type: ["xavier"]
    normalize_and_scale: [true]
    standardize_attrs: [true]

    grad_clip_val: [10, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.001, 0.0005]
    optim|scheduler|step_size: [10, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    batch_size: [128, 256, 512]

zsl_linear_no_ns_std:
  search_type: "random"
  num_experiments: 100

  grid:
    model_type: "linear"
    init|type: ["xavier"]
    normalize_and_scale: [false]
    standardize_attrs: [true]

    grad_clip_val: [10, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.001, 0.0005]
    optim|scheduler|step_size: [10, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    batch_size: [128, 256, 512]


zsl_linear_no_ns_no_std:
  search_type: "random"
  num_experiments: 100

  grid:
    model_type: "linear"
    init|type: ["xavier"]
    normalize_and_scale: [false]
    standardize_attrs: [false]

    grad_clip_val: [10, 100, 1000]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.01, 0.005, 0.001, 0.0005]
    optim|scheduler|step_size: [10, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    batch_size: [128, 256, 512]


different_scalings:
  grid:
    scale: [1., 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]
