inits:
  grid:
    head|init|type: ["proper", "xavier", "kaiming"]
    head|init|mode: ["fan_in", "fan_out"]
    head|init|dist_type: ["uniform", "normal"]

baseline_new:
  grid:
    batch_size: [10]

zsl:
  search_type: "random"
  num_experiments: 250
  grid:
    # val_ratio: [0.1, 0.15, 0.2]
    max_num_epochs: [25, 50, 100]
    optim|kwargs|lr: [0.01, 0.005, 0.004, 0.003, 0.002, 0.001]
    bn_affine: [true, false]
    optim|scheduler|step_size: [10, 50]
    optim|scheduler|gamma: [0.5, 0.9, 1.0]
    label_smoothing: [0.9, 1.0]
    batch_size: [32, 64, 128, 256, 512]
    hid_dim: [256, 512, 1024, 1600]
    scale: [3, 5, 7]

zsl_apy:
  # search_type: "random"
  # num_experiments: 250
  grid:
    # val_ratio: [0.1, 0.15, 0.2]
    max_num_epochs: [25, 50]
    optim|kwargs|lr: [0.002, 0.001, 0.0005]
    bn_affine: [true, false]
    optim|scheduler|step_size: [10, 25, 50]
    optim|scheduler|gamma: [0.5]
    label_smoothing: [0.99, 1.0]
    batch_size: [128, 256]
    hid_dim: [1024, 1600]
