data_dir: "../data/CUB2011"
num_classes: 30
attr_size: 312
max_num_epochs: 1
hp:
  num_mem_samples_per_class: 5
  num_tasks: 4
  pretrained: true
  batch_size: 10
  img_width: 224
  img_height: 224
  mem_batch_size: 128
