task_trainer: "agem"

hp:
  mem_batch_size: 128
  optim_kwargs: {lr: 0.03}

hp_for_datasets:
  awa:
    num_mem_samples_per_class: 20
    pretrained: false
  cub:
    num_mem_samples_per_class: 5
    pretrained: true
