data_dir: "../data/CUB2011"
num_classes: 200
attr_size: 312
max_num_epochs: 1
gpus: []
hp:
  num_mem_samples_per_class: 5
  num_tasks: 17
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  mem_batch_size: 128
