all:
  task_trainer: "agem"
  hp:
    mem_batch_size: 128

awa:
  hp:
    num_mem_samples_per_class: 20
    pretrained: false
cub:
  hp:
    num_mem_samples_per_class: 5
    pretrained: true

# cifar100_embeddings:
#   hp:
#     pretrained: true
#     num_mem_samples_per_class: 10
