all:
  task_trainer: "multi_proto"
  logging:
    save_train_logits: true
    save_prototypes: true
    print_unseen_accuracy: true
    print_forgetting: true
    print_task_guessing_acc: true
    print_final_tasks_performance: true
  hp:
    max_num_epochs: 5
    use_class_attrs: true
    clip_grad: {value: 10}
    optim:
      type: "sgd"
      groups:
        head: {lr: 0.005, momentum: 0.9}
        embedder: {lr: 0.003}
      decrease_lr_coef: 0.9
    use_class_attrs: true
    batch_size: 10

    head:
      has_bias: false
      head_hid_dim: 512
      init:
        type: "proper"
        mode: "fan_in"
        dist_type: "uniform"
        n_classes: 10
      scale: 10
      hid_dim: 512

  validation_sequence: {metric: "harmonic_mean"}
