all:
  task_trainer: "basic"
  logging:
    save_train_logits: true
    save_prototypes: true
    print_unseen_accuracy: true
    print_forgetting: true
  hp:
    use_class_attrs: true
    clip_grad: {value: 10}
    optim:
      groups:
        head: {lr: 0.01, momentum: 0.9}
        embedder: {lr: 0.001}
      # decrease_lr_coef: 0.9
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 1
    batch_size: 10

    head:
      init:
        type: "proper"
        proper_std_type: "fan_in"
        dist_type: "uniform"
        n_classes: 10 # per task
      scale: 10
      hid_dim: 512
      # normalize_attrs: true

  validation_sequence:
    num_tasks: 3
    hpo_grid:
      optim|groups|head|lr: [0.001, 0.005, 0.01, 0.05]
      optim|groups|embedder|lr: [0.001, 0.01]
      head|normalize_attrs: [true, false]
      head|init|dist_type: ["normal", "uniform"]

cub: {hp: {pretrained: true}}
awa: {}
