all:
  inference_batch_size: 512
#  metrics:
#    average_accuracy: true
#    forgetting_measure: true
#    lca_num_batches: 10
#    ausuc: true
  logging:
    save_logits: true
    save_frequency: "iter"
  hp:
    max_num_epochs: 5
    img_target_shape: [224, 224]
    use_class_attrs: true
    batch_size: 10
    model:
      input_type: "resnet18_feat"
      pretrained: false
      type: "simple_classifier"
      hid_dim: 512
    optim: {type: "sgd", kwargs: {lr: 0.03}}
    # optim: {type: "adam", kwargs: {lr: 0.001, betas: [0.0, 0.9]}}

cub:
  data:
    name: "CUB"
    dir: "data/CUB_200_2011"

  lll_setup:
    num_classes_per_task: 20
    num_classes: 200
    num_tasks: 10

  hp:
    model: {pretrained: true}

cub_embedded:
  data:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200
    input_type: "resnet18_feat"
    feat_level: "fc"

  lll_setup:
    num_tasks: 10
    num_classes_per_task: 20

cub_conv_feats:
  data:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200
    input_type: "resnet50_conv"
    feat_level: "conv"

  lll_setup:
    num_tasks: 10
    num_classes_per_task: 20

awa:
  data:
    name: "AWA"
    dir: "data/Animals_with_Attributes2"
    num_classes: 50

  lll_setup:
    num_tasks: 5
    num_classes_per_task: 10

svhn:
  data:
    name: "SVHN"
    dir: "data/SVHN"
    num_classes: &svhn_num_classes 10
    num_img_channels: 3
    img_size: 32

  lll_setup:
    num_classes: *svhn_num_classes
    num_tasks: 10
    num_classes_per_task: 1
