base:
  inference_batch_size: 512
#  metrics:
#    average_accuracy: true
#    forgetting_measure: true
#    lca_num_batches: 10
#    ausuc: true
  logging:
    save_logits: true
    save_frequency: "iter"
  hp:
    max_num_epochs: 5
    img_target_shape: [224, 224]
    use_class_attrs: true
    batch_size: 10
    model:
      type: "simple_classifier"
    optim: {type: "sgd", kwargs: {lr: 0.03}}
    # optim: {type: "adam", kwargs: {lr: 0.001, betas: [0.0, 0.9]}}

datasets:
  cub:
    name: "CUB"
    dir: "data/CUB_200_2011"
    num_classes: 200

    num_tasks: 10
    num_classes_per_task: 20
    num_reserved_classes: 0

  cub_embedded:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200

    num_tasks: 10
    num_classes_per_task: 20
    num_reserved_classes: 0

  awa:
    name: "AWA"
    dir: "data/Animals_with_Attributes2"
    num_classes: 50

    num_tasks: 5
    num_classes_per_task: 10
    num_reserved_classes: 0

  svhn:
    name: "SVHN"
    dir: "data/SVHN"
    num_classes: 10

    num_tasks: 10
    num_classes_per_task: 1
    num_reserved_classes: 0