base:
  max_num_epochs: 1
  inference_batch_size: 512
#  metrics:
#    average_accuracy: true
#    forgetting_measure: true
#    lca_num_batches: 10
#    ausuc: true
  logging:
    save_logits: true
    save_frequency: "iter"
  hp:
    img_target_shape: [224, 224]
    use_class_attrs: true
    batch_size: 10
    model_type: "simple_classifier"

datasets:
  cub:
    name: "CUB"
    dir: "data/CUB2011"
    num_classes: 200

    num_tasks: 10
    num_classes_per_task: 20
    num_reserved_classes: 0

  awa:
    name: "AWA"
    dir: "data/AWA"
    num_classes: 50

    num_tasks: 5
    num_classes_per_task: 10
    num_reserved_classes: 0
