data:
  name: "AWA"
  dir: "data/AWA"
  num_classes: 50
metrics:
  average_accuracy: true
  forgetting_measure: true
  lca_num_batches: 10
max_num_epochs: 1
random_seed: 42
task_trainer: "basic"

num_tasks: 20
num_classes_per_task: 5

hp:
  use_class_attrs: true
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  optim_kwargs: {lr: 0.03}
