all:
  task_trainer: "basic"
  hp:
    use_class_attrs: true
    attrs_head:
      learnable_attrs: false
      use_cls_proj: false
      use_biases: true
      normalize: false
      normalize_feats: false
      scale_value: 1.

cub: {hp: {pretrained: true}}
awa: {}
tiny_imagenet: {}
cifar100: {}

cifar100_embeddings:
  hp:
    use_class_attrs: false
    model:
      type: "feat_classifier"
    classifier:
      data_dim: 512
      hid_dim: 1024
