data:
  name: "CUB"
  dir: "data/CUB2011"
  num_classes: 200
metrics:
  average_accuracy: true
  forgetting_measure: true
  lca_num_batches: 10
  ausuc: true
inference_batch_size: 512
max_num_epochs: 1
random_seed: 42
task_trainer: "basic"
hp:
  use_class_attrs: true
  num_tasks: 20
  pretrained: true
  batch_size: 10
  img_target_shape: [224, 224]
  optim_kwargs: {lr: 0.03}
