data:
  name: "AWA"
  dir: "data/AWA"
  num_classes: 50
max_num_epochs: 1
random_seed: 42
task_trainer: "basic"
hp:
  use_class_attrs: true
  num_tasks: 10
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  optim_kwargs: {lr: 0.03}
