all:
  task_trainer: "basic"
  hp: {}

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

cifar100:
  hp:
    pretrained: false

cifar100_embeddings:
  hp:
    use_class_attrs: false
    model:
      type: "feat_classifier"
    classifier:
      data_dim: 512
      hid_dim: 1024

