trainer: "ClassifierTrainer"
max_num_epochs: 95
val_freq_epochs: 1
hp:
    img_target_shape: [448, 448]
    batch_size: 64
    pretrained: true
    model:
        type: "resnet50"
    optim:
        type: "sgd"
        kwargs:
            lr: 0.001
            momentum: 0.9
            weight_decay: 0.0001
        scheduler:
            type: "step"
            kwargs:
                gamma: 0.1
                step_size: 30
data:
    name: "CUB"
    dir: "data/CUB_200_2011"
    num_classes: 200
