trainer: "ClassifierTrainer"
max_num_epochs: 300
val_freq_epochs: 1
hp:
    batch_size: 256
    pretrained: true
    model:
        type: "resnet-head"
        hid_dim: 512
        resnet_type: 18
    optim:
        type: "adam"
        kwargs:
            weight_decay: 0.0001
        # type: "sgd"
        # kwargs:
        #     lr: 0.01
        #     momentum: 0.95
        #     weight_decay: 0.001
        scheduler:
            type: "step"
            kwargs:
                gamma: 0.1
                step_size: 100
data:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200
