trainer: "ClassifierTrainer"
max_num_epochs: 300
val_freq_epochs: 1
hp:
    batch_size: 256
    pretrained: true
    img_target_shape: 448
    # model:
    #     type: "resnet-head"
    #     hid_dim: 512
    #     input_type: "resnet18_feat"
    model:
        type: "resnet"
        n_resnet_layers: 18
        pretrained: true
    optim:
        type: "adam"
        kwargs:
            weight_decay: 0.0001
        # type: "sgd"
        # kwargs:
        #     lr: 0.01
        #     momentum: 0.95
        #     weight_decay: 0.001
        scheduler:
            type: "step"
            kwargs:
                gamma: 0.1
                step_size: 100
# data:
#     name: "CUB_EMBEDDINGS"
#     dir: "data/CUB_EMBEDDINGS"
#     num_classes: 200
data:
    name: "CUB"
    dir: "data/CUB_200_2011"
    num_classes: 200
