trainer: "ClassifierTrainer"
val_freq_epochs: 1
hp:
    max_num_epochs: 300
    batch_size: 256
    pretrained: true
    img_target_shape: 228
    # model:
    #     type: "resnet-head"
    #     hid_dim: 512
    #     input_type: "resnet18_feat"
    model:
        type: "resnet"
        n_resnet_layers: 18
        pretrained: true
    optim:
        type: "adam"
        kwargs:
            weight_decay: 0.0001
        # type: "sgd"
        # kwargs:
        #     lr: 0.01
        #     momentum: 0.95
        #     weight_decay: 0.001
        scheduler:
            type: "step"
            kwargs:
                gamma: 0.1
                step_size: 100

