all:
  task_trainer: "em"
  hp:
    max_num_epochs: 5
    batch_size: 128
    memory:
      batch_size: 128
      # downsample_size: 64
      loss_coef: 1.
    lowres_training:
      loss_coef: 1.
      distill_loss_coef: 1.
    optim: {"type": "adam", "kwargs": {"lr": 0.001}}

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false
