data_dir: "data/CUB2011"
num_classes: 200
attr_size: 312
max_num_epochs: 1
random_seed: 42
#gpus: []
task_trainer: "ewc"
hp:
  use_class_attrs: true
  num_mem_samples_per_class: 5
  num_tasks: 20
  pretrained: true
  batch_size: 10
  img_target_shape: [224, 224]
  mem_batch_size: 128
  use_agem: false
  ewc:
    reg_coef: 0.1
    fisher_keep_prob: 0.5
  optim_kwargs:
    lr: 0.03
    #weight_decay: 0.00001
