task_trainer: "ewc"
hp:
  fisher_keep_prob: 0.5
  optim_kwargs: {lr: 0.03}

hp_for_datasets:
  cub:
    pretrained: true
    synaptic_strength: 10
    fisher_keep_prob: 0.5
    optim_kwargs: {lr: 0.03}
  awa:
    pretrained: false
    synaptic_strength: 100
