data:
  dir: "data/AWA2"
  num_classes: 50
max_num_epochs: 1
random_seed: 42
task_trainer: "ewc"
hp:
  use_class_attrs: true
  num_mem_samples_per_class: 5
  num_tasks: 20
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  mem_batch_size: 128
  use_agem: false
  synaptic_strength: 100
  fisher_keep_prob: 0.5
  optim_kwargs: {lr: 0.03}
