data:
  name: "AWA"
  dir: "data/AWA"
  num_classes: 50
metrics:
  average_accuracy: true
  forgetting_measure: true
  lca_num_batches: 10
  ausuc: true

max_num_epochs: 1

task_trainer: "ewc"

num_tasks: 17
num_classes_per_task: 5
num_reserved_classes: 15

hp:
  use_class_attrs: true
  num_mem_samples_per_class: 5
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  mem_batch_size: 128
  use_agem: false
  synaptic_strength: 100
  fisher_keep_prob: 0.5
  optim_kwargs: {lr: 0.03}
