trainer: "GANTrainer"
# data:
#     name: "CUB_EMBEDDINGS"
#     dir: "data/CUB_EMBEDDINGS"
#     num_classes: 200
#     input_type: "resnet18_feat"
val_freq_epochs: 10

data:
    name: "MNIST"
    dir: "data/mnist"
    num_classes: 10
    input_type: "mnist_1d"

hp:
    max_num_epochs: 300
    batch_size: 512
    gen_batch_size: 1000

    generator:
        hid_dim: 2048
        z_dim: 512
        emb_dim: &emb_dim 1024
        num_layers: 2
        use_tanh: true
        use_attrs: false

    discriminator:
        type: "cgan"
        hid_dim: 2048
        num_layers: 2
        emb_dim: *emb_dim
        use_attrs: false

    classifier:
        hid_dim: 2048
        max_num_steps: 500
        val_freq_steps: 50
        batch_size: 512

    gen_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.999]}}
    discr_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.999]}}
    # gen_optim: {type: "adam", kwargs: {lr: 0.001}}
    # discr_optim: {type: "adam", kwargs: {lr: 0.001}}
    cls_optim: {type: "adam", kwargs: {lr: 0.001}}

    num_discr_steps_per_gen_step: 10
    loss_coefs:
        gp: 10
        proto: 5

    grad_clipping:
        generator: 100
        discriminator: 100
        classifier: 100
