trainer: "GANTrainer"
data:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200
    input_type: "resnet18_feat"

hp:
    max_num_epochs: 200
    batch_size: 256
    gen_batch_size: 600

    model:
        z_dim: 512
        hid_dim: 1024
        emb_dim: 512
        use_attrs_in_gen: false
        use_attrs_in_discr: false
        input_type: "resnet18_feat"
        share_body_in_discr: false
        gan_type: "cgan"
        cls_hid_dim: 1024
        num_classes: 200

    clf:
        max_num_steps: 300
        batch_size: 256

    # gen_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.999]}}
    # discr_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.999]}}
    gen_optim: {type: "adam", kwargs: {lr: 0.001}}
    discr_optim: {type: "adam", kwargs: {lr: 0.001}}
    cls_optim: {type: "adam", kwargs: {lr: 0.001}}

    num_discr_steps_per_gen_step: 10
    loss_coefs:
        gp: 10
        gen_cls: 1
        discr_cls: 1
        proto: 1

    grad_clipping:
        generator: 100
        discriminator: 100
        classifier: 100

