trainer: "GANTrainer"
data:
    name: "CUB_EMBEDDED"
    dir: "data/CUB_EMBEDDED"
    num_classes: 200
    input_type: "resnet18_feat"

hp:
    max_num_epochs: 100

    model:
        z_dim: 256
        hid_dim: 1024
        emb_dim: 512
        use_attrs_in_gen: false
        use_attrs_in_discr: false
        input_type: "resnet18_feat"
        feat_level: "fc"
        share_body_in_discr: false
        conditional_discr: false
        cls_hid_dim: 1024
        num_classes: 200

    clf:
        max_num_steps: 100
        batch_size: 256

    gen_optim: {type: "adam", kwargs: {lr: 0.001}}
    discr_optim: {type: "adam", kwargs: {lr: 0.001}}
    cls_optim: {type: "adam", kwargs: {lr: 0.001}}

    num_discr_steps_per_gen_step: 5
    loss_coefs:
        gp: 10
        gen_cls: 1
        discr_cls: 1

    grad_clipping:
        generator: 100
        discriminator: 100
        classifier: 100
        embedder: 100

    batch_size: 256
