trainer: "GANClassifierTrainer"
val_freq_iters: 100
hp:
    max_num_iters: 1000
    batch_size: 128
    # gan_checkpoint_path: "experiments/gm_gan--svhn--1-00001/checkpoints/model-task-9.pt"
    # gan_config_path: "experiments/gm_gan--svhn--1-00001/config.yml"
    gan_checkpoint_path: "experiments/gm_gan--cifar100--1-00002/checkpoints/model-task-9.pt"
    gan_config_path: "experiments/gm_gan--cifar100--1-00002/config.yml"


    classifier:
        pretrained: true
        resnet_n_layers: 18
    generator: {dim: 32, z_dim: 128}
    discriminator: {dim: 32}

data:
    name: "CIFAR100"
    dir: "data/CIFAR100"
    num_classes: 100
    num_img_channels: 3
    img_size: 32
    source: "gan_model"
