all:
  logging:
    save_train_logits: true
    save_prototypes: true
    print_unseen_accuracy: true
    print_forgetting: true
  inference_batch_size: 128
  task_trainer: "multi_proto"
  hp:
    clip_grad: {value: 10}
    optim:
      groups:
        head: {lr: 0.01, momentum: 0.9}
        embedder: {lr: 0.01}
      kwargs: {}
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 1
    batch_size: 10
    head:
      init:
        type: "xavier_normal"
        gain: 1.0
      model_type: "gaussian"
      hid_dim: 512
      gaussian_approx_rank: 5
      # aggregation_type: "gmm"
      # normalize_cov: false
      # scale: 0.2
      cov_diag_transform: "tanh"

    diagonal_cov_reg:
      loss_magnitude: 0.0
      per_class: false
      batch_size: 100

  validation_sequence:
    num_tasks: 3
    hpo_grid:
      clip_grad|value: [10, 100]
      optim|groups|head|lr: [0.01, 0.001, 0.0001]
      # optim|groups|head|momentum: [0.0, 0.9]
      # optim|groups|embedder|lr: [0.01, 0.001]
      # head|init|type: ["xavier_normal", "xavier_uniform"]

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
