all:
  logging:
    save_train_logits: true
    save_prototypes: true
    print_unseen_accuracy: true
    print_forgetting: true
  inference_batch_size: 128
  task_trainer: "multi_proto"
  hp:
    clip_grad: {value: 10}
    optim: {kwargs: {lr: 0.001}}
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 1
    batch_size: 10

    head:
      model_type: "gaussian"
      init: {type: "xavier_normal"}
      hid_dim: 512
      gaussian_approx_rank: 5
      cov_diag_transform: "tanh"

    diagonal_cov_reg:
      loss_magnitude: 0.0
      per_class: false
      batch_size: 100

  validation_sequence:
    num_tasks: 3
    hpo_grid:
      clip_grad|value: [10, 100]
      optim|kwargs|lr: [0.01, 0.001, 0.0001]
      head|init|type: ["xavier_normal", "xavier_uniform"]
      head|cov_diag_transform: ["tanh", "sigmoid", "elu"]

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
