all:
  task_trainer: "genmem_gan"

  hp:
    use_class_attrs: false

    generator: {dim: 32, z_dim: 128}
    discriminator: {dim: 32}

    gen_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.9]}}
    discr_optim: {type: "adam", kwargs: {lr: 0.0001, betas: [0.0, 0.9]}}

    num_discr_steps_per_gen_step: 5
    gp_coef: 10
    distill_loss_coef: 1.
    batch_size: 64
    cls_loss_coef_discr: 1.
    cls_loss_coef_gen: 1.
    distill_batch_size: 100

svhn:
  plotting:
    samples_freq: 2000
    num_samples_per_class: 100
  hp:
    img_target_shape: [32, 32]
    num_iters_per_task: 40000

cub:
  plotting:
    samples_freq: 10000
    num_samples_per_class: 5
  hp:
    num_iters_per_task: 100000

awa:
  data:
    classes_to_use: [0, 1, 2, 3]
    num_classes: 4
    num_classes_per_task: 1
    num_tasks: 4
    img_size: 64

  plotting:
    # samples_freq: 5
    samples_freq: 10000
    num_samples_per_class: 5

  hp:
    img_target_shape: [64, 64]
    # num_iters_per_task: 10
    num_iters_per_task: 100000

    model:
      type: "genmem_gan_64x64"
      emb_dim: 256
      z_dim: 128
