task_trainer: "genmem_gan"
hp:
  model_type: "genmem_gan"
  use_class_attrs: false

hp_for_datasets:
  svhn:
    num_iters_per_class: 40000

    model_config:
      z_dim: 128
      gen_dim: 32
      discr_dim: 32
      num_img_channels: 3
      img_size: 32
      num_classes: 10

    gen_optim:
      type: "adam"
      kwargs: {lr: 0.0001, betas: [0.0, 0.9]}

    discr_optim:
      type: "adam"
      kwargs: {lr: 0.0001, betas: [0.0, 0.9]}

    num_discr_steps_per_gen_step: 5
    gp_coef: 10
    distill_loss_coef: 0.01
    batch_size: 53
    cls_loss_coef_discr: 1.
    cls_loss_coef_gen: 1.
    distill_batch_size: 100
