all:
  task_trainer: "joint"
  hp:
    optim: {type: "sgd", kwargs: {lr: 0.03}}
    # optim: {type: "adam", kwargs: {lr: 0.001}}
    # optim: {type: "adam", kwargs: {lr: 0.001, betas: [0.0, 0.9]}}
    reinit_after_each_task: false

cub_embeddings:
  hp:
    max_num_epochs: 50
    model:
      type: "feat_classifier"
      input_type: "resnet18_feat"
      hid_dim: 512
      num_classes: 200
    optim: {type: "adam", kwargs: {lr: 0.001}}
  data:
    input_type: "resnet18_feat"

cub:
  hp:
    max_num_epochs: 5
    pretrained: true

awa:
  hp:
    max_num_epochs: 5
    pretrained: false
