all:
    task_trainer: "lat_gm"
    hp:
        use_class_attrs: true

        model:
            type: "lat_gm"
            z_dim: 256
            hid_dim: 1024
            feat_dim: 512
            emb_dim: 512
            num_img_channels: 3
            attr_output_dim: 512
            use_attrs_in_gen: true
            resnet_type: 18
            feat_level: "conv"

        gen_optim:
            type: "adam"
            kwargs: {lr: 0.0001, betas: [0.0, 0.9]}

        discr_optim:
            type: "adam"
            kwargs: {lr: 0.0001, betas: [0.0, 0.9]}

        clf_optim:
            type: "sgd"
            kwargs: {lr: 0.001}

        num_discr_steps_per_gen_step: 5
        loss_coefs:
            gp: 10
            distill: 1.
            discr_cls: 1.
            gen_cls: 1.

        batch_size: 64
        distill_batch_size: 500

        # Regularizing feature extractor
        synaptic_strength: 0.01
        fisher_keep_prob: 0.5
        reg_strategy: "ewc"

        # Creativity losses
        creativity:
            enabled: true
            start_iter: -1
            hall_batch_size: 300
            adv_coef: 0.01
            entropy_coef: 0.01


cub:
    hp:
        num_iters_per_task: 100
        model:
            num_classes: 200
            pretrained: true

awa:
    hp:
        num_iters_per_task: 5000
        model:
            num_classes: 50
            pretrained: false
