all:
  task_trainer: "mas"
  hp:
    optim: {type: "sgd", kwargs: {lr: 0.03}}
    synaptic_strength: 0.1

cub_embeddings:
  hp:
    max_num_epochs: 10
    model:
      type: "feat_classifier"
      input_type: "resnet18_feat"
      hid_dim: 512
      num_classes: 200
    optim: {type: "adam", kwargs: {lr: 0.001}}
  data:
    input_type: "resnet18_feat"
