task_trainer: "mas"

hp:
  use_class_attrs: true
  batch_size: 10
  img_target_shape: [224, 224]
  optim_kwargs: {lr: 0.03}

hp_for_datasets:
  cub:
    pretrained: true
    synaptic_strength: 0.1
  awa:
    pretrained: false
    synaptic_strength: 0.1
