all:
  task_trainer: "mas"
  hp:
    optim: {type: "sgd", kwargs: {lr: 0.03}}

cub_embedded:
  hp:
    max_num_epochs: 10
    model:
      type: "feat_classifier"
      resnet_type: 18
      hid_dim: 512
      num_classes: 200
    optim: {type: "adam", kwargs: {lr: 0.001}}
  data:
    resnet_type: 18

cub:
  hp:
    synaptic_strength: 0.1
awa:
  hp:
    synaptic_strength: 0.1
