data:
  name: "CUB"
  dir: "data/CUB2011"
  num_classes: 200
metrics:
  average_accuracy: true
  forgetting_measure: true
  lca_num_batches: 10
  ausuc: true
max_num_epochs: 1

task_trainer: "mas"

num_tasks: 17
num_classes_per_task: 10
num_reserved_classes: 30

hp:
  use_class_attrs: true
  pretrained: true
  batch_size: 10
  img_target_shape: [224, 224]
  synaptic_strength: 0.1
  optim_kwargs: {lr: 0.03}
