data:
  name: "AWA"
  dir: "data/AWA"
  num_classes: 50
max_num_epochs: 1

task_trainer: "mas"
metrics:
  average_accuracy: true
  forgetting_measure: true
  lca_num_batches: 10
  ausuc: true

num_tasks: 17
num_classes_per_task: 5
num_reserved_classes: 15

hp:
  use_class_attrs: true
  pretrained: false
  batch_size: 10
  img_target_shape: [224, 224]
  synaptic_strength: 0.1
  optim_kwargs: {lr: 0.03}
