task_trainer: "mergazsl"
batch_size: 64

hp:
  max_num_epochs: 100
  embed_data: true
  clip_grad_norm: 100

  model_type: "feat_gan_classifier"
  model_config:
    z_dim: 100
    # prediction_strategy: "nearest_neighbor"
    # num_hallicinated_samples_per_class: 100
    prediction_strategy: "classifier"
    feat_dim: 512
    attr_input_dim: 312
    attr_output_dim: 512
    hid_dim: 512
    gen_optim_kwargs: {lr: 0.01}
    discr_optim_kwargs: {lr: 0.01}
    cls_optim_kwargs: {lr: 0.01}
    num_discr_steps_per_gen_step: 1
    centroid_reg_coef: 1
    distill_batch_size: 100
    model_distill_coef: 0.001

  use_joint_cls_training: true
  joint_clf_training_batch_size: 100
  joint_cls_training_loss_coef: 1

hp_for_datasets:
  cub:
    pretrained: true
    model_config:
      num_classes: 200
