all:
  task_trainer: "multi_proto"
  hp:
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10
    head:
      type: "deterministic_linear"
      num_prototypes: 1
      hid_dim: 512
      normalize: true
      scale_value: 10.
      combine_strategy: "sum"

      logits_scaling: # Scaling by num_prototypes and scale_value
          enabled: false
          scale_value: 1.

      senet:
        enabled: true
        reduction_dim: 16

    # head:
    #   type: "embedding_based"
    #   num_prototypes: 10
    #   hid_dim: 512
    #   normalize: true
    #   scale_value: 5.
    #   combine_strategy: "sum"
    #   context:
    #     # type: "gaussian_noise"
    #     # type: "transformed_gaussian_noise"
    #     # use_activation: true
    #     same_for_each_class: true
    #     # proto_emb_size: 512
    #     # z_size: 64
    #     # std: 1.
    #   fusing_type: "concat"

    push_protos_apart:
      enabled: false
      loss_coef: 1

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
