all:
  task_trainer: "multi_proto"
  hp:
    clip_grad: {value: 10}
    optim:
        groups:
            head: {lr: 0.005, momentum: 0.9}
            embedder: {}
        kwargs: {lr: 0.003}
    use_class_attrs: true
    normalized_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10

    diagonal_cov_reg:
        loss_coef: 0.0
        per_class: false
        batch_size: 100

    triplet_loss:
      enabled: false
      coef: 0.0

    generative_training:
      loss_coef: 0.0
      num_protos: 20 # num images per class
      type: "mmd"
      cov_diff_coef: 0.0

    reverse_clf:
      loss_coef: 0.0
      n_imgs_per_class: 10

    protos_clf_loss_coef: 0.0
    push_protos_apart_loss_coef: 0.0

    head:
      type: "random_embeddings"
      num_prototypes: 50
      hid_dim: 512
      fusing_type: "concat"
      after_fuse_transform_layers: [512, 512]
      after_fuse_activation: "tanh"
      after_fuse_identity_init: true
      attrs_transform_layers: [312]
      use_tanh_on_top: false # To be similar to gazsl
      aggregation_type: "average_prototypes"

      feats_noise_std: 0.0

      noise:
        transform_layers: [100]
        same_for_each_class: false
        std: 0.0

      golden_proto:
        enabled: false
        weight: 1.0

      scale:
        type: "constant"
        value: 10

      dae:
        enabled: false
        encoder_layers: [512, 256, 100]
        input_noise_type: "gaussian"
        input_std: 1.
        # input_dropout_p: 0.5
        codes_std: 0.1
        loss_coef: 0.0

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
