all:
  task_trainer: "multi_proto"
  hp:
    optim: {kwargs: {lr: 0.005}}
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10

    head:
      type: "dropout_attrs"
      num_prototypes: 50
      hid_dim: 512
      attrs_transform_layers: [312, 1024, 512]
      use_tanh_on_top: false

      # How to combine the predictions from different prototypes
      aggregation_type: "average_prototypes"

      dropout:
        type: "gaussian"
        std: 1.0

      scale:
        type: "constant"
        value: 10

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
