all:
  logging:
  #   save_knn_logits: True
  #   save_golden_logits: True
    save_prototypes: True
  inference_batch_size: 64
  task_trainer: "multi_proto"
  hp:
    clip_grad: {value: 10}
    optim:
        groups:
            head: {lr: 0.005, momentum: 0.9}
            embedder: {}
        kwargs: {lr: 0.003}
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10

    diagonal_cov_reg:
      loss_coef: 0.0
      per_class: false
      batch_size: 100

    triplet_loss:
      enabled: false
      coef: 0.0

    generative_training:
      loss_coef: 0.0
      num_protos: 20 # num images per class
      type: "mmd"
      cov_diff_coef: 0.0

    reverse_clf:
      loss_coef: 0.0
      n_imgs_per_class: 20

    pull_golden_protos:
      loss_coef: 0.0
      n_imgs_per_class: 20

    fake_clf:
      loss_coef: 0.0

    protos_clf_loss_coef: 0.0
    push_protos_apart_loss_coef: 0.0

    head:
      model_type: "linear"

      common:
        type: "random_embeddings"
        num_prototypes: 1
        hid_dim: 512
        fusing:
          type: "concat"
        use_tanh_on_top: false # Enable to be similar to gazsl
        aggregation_type: "average_prototypes"
        test_aggregation_type: "average_prototypes"

        attrs_transform:
          layers: [312]
          identity_init: false

        noise:
          transform_layers: [100]
          identity_init: false
          same_for_each_class: false
          std: 0.0

        golden_proto:
          enabled: false
          weight: 1.0

        scale:
          type: "constant"
          value: 10

      linear:
        fusing:
          activation: "none"

        after_fuse_transform:
          layers: [512]
          identity_init: false

      deep:
        fusing:
          activation: "tanh"
        after_fuse_transform:
          layers: [512, 512]
          identity_init: true
          bias: false
        renormalize_attrs_to_gaussian: true

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
