all:
  task_trainer: "basic"
  hp:
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10
    head:
      type: "deterministic_linear"
      num_prototypes: 1
      hid_dim: 512
      normalize: false
      scale_value: 1.

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
