all:
  task_trainer: "multi_proto"
  hp:
    use_class_attrs: true
    img_target_shape: [256, 256]
    max_num_epochs: 5
    batch_size: 10

    # head:
    #   output_dist: "normal"
    #   type: "multi_headed"
    #   num_prototypes: 1
    #   hid_dim: 512
    #   scale_value: 10.
    #   combine_strategy: "mean"
    #   embedder_hidden_layers: []
    #   use_final_activation: false

    #   senet:
    #     enabled: false
    #     reduction_dim: 16

    head:
      output_dist: "von_mises"
      type: "random_embeddings"
      num_prototypes: 1
      hid_dim: 512
      combine_strategy: "mean"
      fusing_type: "concat"
      after_fuse_transform_layers: [512]
      attrs_transform_layers: [312]

      noise:
        transform_layers: [16]
        same_for_each_class: false
        std: 0.0

      scale:
        # type: "predict_from_logits"
        type: "constant"
        layers_sizes: [200, 256, 1]
        value: 10

    push_protos_apart:
      enabled: false
      loss_coef: 1

cub:
  hp:
    pretrained: true

awa:
  hp:
    pretrained: false

tiny_imagenet: {}
