trainer: "ZSLTrainer"
dataset: "awa2"
val_freq_epochs: 10
hp:
  max_num_epochs: 1000
  batch_size: 512
  grad_clip_val: 100
  hid_dim: 1600
  feat_dim: 2048
  optim:
    type: "adam"
    kwargs:
      lr: 0.0001

data:
  awa2:
    seen_classes: [2,3,4,5,7,9,10,11,12,13,14,16,18,19,20,24,25,21,26,28,31,32,34,35,36,37,38,41,42,44,45,48,39,43,17,0,1,27,47,15]
    unseen_classes: [22,49,29,23,8,33,6,46,30,40]
    dir: "/tmp/skoroki/czsl/data/awa2_feats"
    num_classes: 50
    attrs_dim: 85
